#!/usr/bin/env node

const exec = require('../src/exec');

(async function() {
  const exists = await require('../src/checktag')();
  if (exists) return;
  await require('../src/generatechangelog')();
  await require('../src/gitaddcommitpush')({
    files: ['CHANGELOG.md'],
    commitMsg: 'chore: update changelog'
  });
  await require('../src/releasetag')();
  await exec(`npm publish --access=public`);
})();
