#!/usr/bin/env node

const exec = require('../src/exec');

(async function() {
  const exists = require('../src/checktag')();
  if (exists) return;
  await require('../src/generatechangelog')();
  require('../src/getrollupconfig')({
    files: ['misc/*'],
    commitMsg: 'chore: update changelog'
  });
  await require('../../src/releasetag')();
  await exec(`npm publish --access=public`);
})();
